### ISSUE TITLE
Questions regarding a better use of this example repo

### ISSUE THREAD

**Issue by simkimsia** [lorenzo/cakephp3-examples#2]
Great talk Lorenzo!

Good idea to have an example repo

My questions are:

a) can you link the slides to the advanced querying talk in the README?

b) Can you append the .sql schema for the countries, cities, and languages so it is easier for me to wrap my mind around the example?

**Comment by lorenzo** [comment]
Fixed :)

**Comment by simkimsia** [comment]
great! thanks :+1:

**Comment by simkimsia** [comment]
@lorenzo Sorry but your world.sql in https://github.com/lorenzo/cakephp3-examples/blob/master/config/Schema/world.sql is actually NOT showing the countries, languages, cities schema.

**Comment by lorenzo** [comment]
LOL, I uploaded the other one, sorry

**Comment by lorenzo** [comment]
Fixed!
