### ISSUE TITLE
Warning: require(C:\wamp\www\cakephp3-examples-master\vendor\autoload.php): 

### ISSUE THREAD

**Issue by SanjayChaudhary02** [lorenzo/cakephp3-examples#3]
No such file or directory in C:\wamp\www\cakephp3-examples-master\config\bootstrap.php on line 23

vendor/autoload.php is missing can you please help me to solve it. i am fresh on cakephp

**Comment by neetmon** [comment]
.gitignore state that 
/vendor/*
/config/app.php
/tmp/*
/logs/*

you just need to run composer update on your cloned cake project and add your own app.php

**Comment by lorenzo** [comment]
You need to run `composer install`
